sonar.projectKey=deandeakin_LLMEnhancedLearningAssistant-DevOps
sonar.organization=deandeakin
sonar.host.url=https://sonarcloud.io

sonar.projectName=LLM Enhanced Learning Assistant
sonar.sourceEncoding=UTF-8

sonar.sources=app/src/main/java,backend
sonar.exclusions=backend/node_modules/**,backend/server.test.js,app/build/**,**/androidTest/**

sonar.java.binaries=app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300